import { useState, type ReactNode } from 'react'
import { EducationalCard } from '../shared/components/EducationalCard'
import { LessonFlow, type LessonStepDefinition } from '../shared/components/LessonFlow'
import { TeacherSpace } from '../shared/teacher/TeacherSpace'

interface Props { onProgressChange?: (value: number) => void; onFinish?: () => void }
type Question = { number: number; prompt: string; options?: string[]; answer: string; section: string }

const separate = [
  ['المتكلم', 'أنا', 'للمتكلم المفرد', 'أنا أقرأُ.'], ['المتكلم', 'نحن', 'للمتكلمين', 'نحن نقرأُ.'],
  ['المخاطب', 'أنتَ', 'مذكر مفرد', 'أنتَ مجتهدٌ.'], ['المخاطب', 'أنتِ', 'مؤنث مفرد', 'أنتِ مجتهدةٌ.'], ['المخاطب', 'أنتما', 'اثنان أو اثنتان', 'أنتما مجتهدانِ.'], ['المخاطب', 'أنتم', 'جماعة الذكور', 'أنتم مجتهدونَ.'], ['المخاطب', 'أنتنَّ', 'جماعة الإناث', 'أنتنَّ مجتهداتٌ.'],
  ['الغائب', 'هو', 'مذكر مفرد', 'هو يدرسُ.'], ['الغائب', 'هي', 'مؤنث مفرد', 'هي تدرسُ.'], ['الغائب', 'هما', 'اثنان أو اثنتان', 'هما يدرسانِ.'], ['الغائب', 'هم', 'جماعة الذكور', 'هم يدرسونَ.'], ['الغائب', 'هنَّ', 'جماعة الإناث', 'هنَّ يدرسنَ.'],
]
const solved = [
  ['أنا أحبُّ القراءةَ.', 'أنا: ضمير منفصل للمتكلم.'], ['هي تكتبُ الواجبَ.', 'هي: ضمير منفصل للغائب، ويدل على مفرد مؤنث.'], ['أنتم تحبونَ الرياضةَ.', 'أنتم: ضمير منفصل للمخاطب، ويدل على الجمع.'], ['هذا قلمي.', 'الياء في قلمي: ضمير متصل يدل على المتكلم.'], ['أخذَ سامرٌ كتابَهُ.', 'الهاء في كتابه: ضمير متصل يعود على سامر.'], ['فتحتْ مريمُ حقيبتَها.', 'ها في حقيبتها: ضمير متصل يعود على مريم.'], ['نحن نحبُّ وطنَنا.', 'نحن ضمير منفصل للمتكلمين، ونا في وطننا ضمير متصل.'], ['أكتبُ واجبي.', 'الفاعل ضمير مستتر تقديره أنا، والياء في واجبي ضمير متصل؛ فقد تحتوي الجملة أكثر من ضمير.'],
]
const questions: Question[] = [
  {number:1,section:'السؤال الأول: اختر الإجابة الصحيحة',prompt:'الضمير الذي يدل على المتكلم المفرد هو:',options:['هو','أنا','أنتَ','نحن'],answer:'أنا'},
  {number:2,section:'السؤال الأول: اختر الإجابة الصحيحة',prompt:'الضمير المناسب لمريم هو:',options:['هو','هم','هي','نحن'],answer:'هي'},
  {number:3,section:'السؤال الأول: اختر الإجابة الصحيحة',prompt:'الضمير المناسب لخالد وسامر هو:',options:['هو','هم','هما','هنَّ'],answer:'هما'},
  {number:4,section:'السؤال الأول: اختر الإجابة الصحيحة',prompt:'الضمير المناسب لجماعة من الطالبات هو:',options:['هم','هنَّ','هما','نحن'],answer:'هنَّ'},
  {number:5,section:'السؤال الأول: اختر الإجابة الصحيحة',prompt:'أي الكلمات الآتية تحتوي على ضمير متصل؟',options:['مدرسة','كتابه','قلم','ولد'],answer:'كتابه'},
  {number:6,section:'السؤال الثاني: صح أم خطأ؟',prompt:'كلمة أنا ضمير منفصل.',options:['صح','خطأ'],answer:'صح'},
  {number:7,section:'السؤال الثاني: صح أم خطأ؟',prompt:'كلمة هي تدل على مذكر مفرد.',options:['صح','خطأ'],answer:'خطأ'},
  {number:8,section:'السؤال الثاني: صح أم خطأ؟',prompt:'الضمير هما يمكن أن يدل على اثنين أو اثنتين.',options:['صح','خطأ'],answer:'صح'},
  {number:9,section:'السؤال الثاني: صح أم خطأ؟',prompt:'الهاء في كلمة كتابه ضمير متصل.',options:['صح','خطأ'],answer:'صح'},
  {number:10,section:'السؤال الثاني: صح أم خطأ؟',prompt:'الضمير نحن من ضمائر المخاطب.',options:['صح','خطأ'],answer:'خطأ'},
  {number:11,section:'السؤال الثالث: استخرج الضمير وحدد نوعه',prompt:'أنا أحبُّ اللغةَ العربيةَ. الضمير؟ منفصل أم متصل؟ متكلم أم مخاطب أم غائب؟',answer:'أنا؛ منفصل؛ متكلم.'},
  {number:12,section:'السؤال الثالث: استخرج الضمير وحدد نوعه',prompt:'أخذَ خالدٌ كتابَهُ. ما الضمير المتصل؟ وعلى من يعود؟',answer:'الهاء (ـه) في كتابه؛ يعود على خالد.'},
  {number:13,section:'السؤال الثالث: استخرج الضمير وحدد نوعه',prompt:'هي تساعدُ أمَّها. اكتب الضمير المنفصل والضمير المتصل.',answer:'هي؛ وها في أمها.'},
  {number:14,section:'السؤال الرابع: ضع الضمير المناسب',prompt:'______ طالبٌ مجتهدٌ. المطلوب: ضمير غائب مفرد مذكر.',answer:'هو طالبٌ مجتهدٌ.'},
  {number:15,section:'السؤال الرابع: ضع الضمير المناسب',prompt:'______ طالبةٌ مجتهدةٌ. المطلوب: ضمير غائب مفرد مؤنث.',answer:'هي طالبةٌ مجتهدةٌ.'},
  {number:16,section:'السؤال الرابع: ضع الضمير المناسب',prompt:'______ نحبُّ مدرستنا. المطلوب: ضمير متكلم للجمع.',answer:'نحن نحبُّ مدرستنا.'},
  {number:17,section:'السؤال الرابع: ضع الضمير المناسب',prompt:'______ تدرسنَ جيدًا. المطلوب: ضمير مخاطب لجماعة الإناث.',answer:'أنتنَّ تدرسنَ جيدًا.'},
  {number:18,section:'السؤال الخامس: صحح الخطأ',prompt:'مريمُ تحبُّ القراءةَ، هو تقرأُ كلَّ يومٍ. اكتب الجملة بصورة صحيحة.',answer:'مريمُ تحبُّ القراءةَ، هي تقرأُ كلَّ يومٍ.'},
  {number:19,section:'السؤال الخامس: صحح الخطأ',prompt:'خالدٌ وسامرٌ يدرسانِ معًا، هم مجتهدانِ. استبدل الضمير غير المناسب.',answer:'خالدٌ وسامرٌ يدرسانِ معًا، هما مجتهدانِ.'},
  {number:20,section:'السؤال السادس: سؤال تفكير',prompt:'عادَ أحمدُ إلى منزلِهِ، ثم فتحَ كتابَهُ. أ. استخرج الضمير المتصل المتكرر. ب. على من يعود؟ ج. لماذا استُعمل بدل تكرار أحمد؟',answer:'الهاء (ـه) في منزله وكتابه؛ يعود على أحمد؛ لتجنب تكرار اسمه وجعل الكلام أكثر سلاسة.'},
]

export function LessonFive({ onProgressChange, onFinish }: Props) {
 const [activityAnswers,setActivityAnswers]=useState<Record<string,string>>({}); const [activityChecked,setActivityChecked]=useState<Record<string,boolean>>({});
 const [testAnswers,setTestAnswers]=useState<Record<number,string>>({}); const [testChecked,setTestChecked]=useState(false)
 const steps: LessonStepDefinition[] = [
  step('intro','الدرس الخامس: الضمائر المنفصلة والمتصلة','البداية','👋',<EducationalCard title="الدرس الخامس: الضمائر المنفصلة والمتصلة" eyebrow="عنوان الدرس" tone="accent"><div className="pronoun-hero"><bdi>أنا</bdi><span>•</span><bdi>أنتَ</bdi><span>•</span><bdi>هو</bdi></div><p>نتعلم كيف يحل الضمير محل الاسم، وكيف يأتي منفصلًا أو متصلًا، مع فكرة أولية عن الضمير المستتر.</p></EducationalCard>),
  step('objectives','أهداف الدرس','البداية','🎯',<><p>في نهاية هذا الدرس يُتوقَّع من الطالب أن يستطيع:</p><ul className="check-list"><li>فهم معنى الضمير وسبب استخدامه.</li><li>التمييز بين الاسم الظاهر والضمير.</li><li>معرفة ضمائر المتكلم والمخاطب والغائب.</li><li>معرفة الضمائر المنفصلة الأساسية وأهم الضمائر المتصلة.</li><li>تحديد ما يعود عليه الضمير واستخدامه بطريقة صحيحة.</li><li>تجنب الأخطاء الشائعة.</li><li>إجراء إعراب أولي بسيط لبعض الضمائر دون الدخول في التفاصيل المتقدمة.</li></ul></>),
  step('what-pronoun','1–2. ما الضمير؟ ولماذا نستخدمه؟','مفهوم الضمير','💬',<><p>تأمل: <strong>جاءَ خالدٌ إلى المدرسةِ، ثم دخلَ خالدٌ إلى الصفِّ، وفتحَ خالدٌ كتابَه.</strong></p><p>بطريقة أفضل: <strong>جاءَ خالدٌ إلى المدرسةِ، ثم دخلَ هو إلى الصفِّ، وفتحَ كتابَه.</strong></p><Rule>الضمير: كلمة تدل على متكلم أو مخاطب أو غائب، وتُستعمل غالبًا بدلًا من تكرار الاسم.</Rule><p>مثل: <strong>أنا – نحن – أنتَ – أنتِ – هو – هي – هم</strong>.</p><p><strong>مريمُ مجتهدةٌ. هي تحبُّ القراءةَ.</strong> كلمة هي تعود على مريم.</p><p>نستخدم الضمائر لتجنب التكرار ولجعل الكلام أسهل وأجمل: <strong>سافرَ سامرٌ، وهو سيعودُ غدًا.</strong></p></>),
  step('noun-pronoun','3. الاسم الظاهر والضمير','مفهوم الضمير','🏷️',<><p>الاسم الظاهر هو المذكور بلفظه: <strong>محمد – سارة – الطالب – المعلمة – الكتاب</strong>. أما الضمير فيأتي بدلًا من الاسم أو يدل عليه.</p><Compare a="محمدٌ طالبٌ مجتهدٌ." b="هو يحبُّ العلمَ." an="محمد: اسم ظاهر" bn="هو: ضمير يعود على محمد"/><Compare a="سارةُ تقرأُ القصةَ." b="هي تحبُّ القراءةَ." an="سارة: اسم ظاهر" bn="هي: ضمير يعود على سارة"/></>),
  step('three-persons','4. المتكلم والمخاطب والغائب','مفهوم الضمير','🗣️',<><div className="pronoun-three"><article><strong>المتكلم</strong><p>الشخص الذي يتحدث: أنا طالبٌ. نحن طلابٌ.</p><bdi>أنا – نحن</bdi></article><article><strong>المخاطب</strong><p>الشخص الذي أتحدث إليه مباشرةً: أنتَ مجتهدٌ، أنتِ مجتهدةٌ.</p><bdi>أنتَ – أنتِ – أنتما – أنتم – أنتنَّ</bdi></article><article><strong>الغائب</strong><p>الشخص الذي نتحدث عنه، لا إليه: هو مجتهدٌ، هي مجتهدةٌ.</p><bdi>هو – هي – هما – هم – هنَّ</bdi></article></div></>),
  step('separate-definition','5. الضمائر المنفصلة','الضمائر المنفصلة','🔓',<><Rule>منفصلة: تُكتب كلمةً مستقلة، ولا تكون ملتصقة بكلمة أخرى.</Rule><Compare a="أنا أدرسُ." b="هو يكتبُ." an="أنا كلمة مستقلة" bn="هو كلمة مستقلة"/><p>سنبدأ بضمائر الرفع المنفصلة، وهي الأكثر أهمية للمبتدئ.</p></>),
  step('speaker-addressee','6–7. ضمائر المتكلم والمخاطب','الضمائر المنفصلة','👥',<><PronounTable rows={separate.slice(0,7)}/><p><strong>أنا أحبُّ اللغةَ العربيةَ. نحن نذهبُ إلى المدرسةِ.</strong></p><ul><li>أنتَ: ولد واحد.</li><li>أنتِ: بنت واحدة.</li><li>أنتما: اثنان أو اثنتان.</li><li>أنتم: مجموعة ذكور، وقد تستعمل لجماعة فيها ذكور وإناث.</li><li>أنتنَّ: مجموعة إناث.</li></ul></>),
  step('absent','8. ضمائر الغائب','الضمائر المنفصلة','👤',<><PronounTable rows={separate.slice(7)}/><p><strong>عمرٌ طالبٌ. هو مجتهدٌ.</strong></p><p><strong>مريمُ طالبةٌ. هي مجتهدةٌ.</strong></p><p><strong>خالدٌ وسامرٌ صديقانِ. هما يلعبانِ.</strong></p><p><strong>الطلابُ حاضرونَ. هم يستمعونَ إلى المعلمِ.</strong></p><p><strong>الطالباتُ حاضراتٌ. هنَّ يستمعنَ إلى المعلمةِ.</strong></p></>),
  step('complete-table','9. جدول الضمائر المنفصلة للحفظ','الضمائر المنفصلة','📋',<><PronounTable rows={separate}/><Rule>لدينا 12 ضميرًا منفصلًا: أنا، نحن، أنتَ، أنتِ، أنتما، أنتم، أنتنَّ، هو، هي، هما، هم، هنَّ.</Rule></>),
  step('attached-definition','10–11. الضمير المتصل وبماذا يتصل؟','الضمائر المتصلة','🔗',<><p>الضمير المنفصل يُكتب وحده: <strong>هو – هي – أنا – نحن</strong>. أما المتصل فلا يأتي وحده، بل يتصل بكلمة أخرى.</p><p className="big-example"><bdi>كتابُهُ</bdi></p><p>الهاء (ـه) ضمير متصل، والمعنى: الكتاب الذي يخصه. في: <strong>أخذَ خالدٌ كتابَهُ</strong> تعود الهاء على خالد.</p><Rule>يمكن أن تتصل الضمائر بـ: الاسم – الفعل – الحرف. وسنأخذها بالتدريج.</Rule></>),
  step('attached-nouns','12–13. الضمير المتصل بالاسم','الضمائر المتصلة','📚',<><div className="chip-grid">{['كتابي = كتاب + ي','كتابنا = كتاب + نا','كتابكَ = كتاب + كَ','كتابكِ = كتاب + كِ','كتابهُ = كتاب + ه','كتابها = كتاب + ها','كتابكم = كتاب + كم','كتابهم = كتاب + هم','كتابهنَّ = كتاب + هنَّ'].map(x=><bdi key={x}>{x}</bdi>)}</div><p><strong>هذا كتابي. هذه مدرستنا. أين قلمك؟ هذا منزلهم.</strong></p><p>عندما يتصل الضمير بالاسم، يدل غالبًا على الملكية أو الاختصاص: قلمي = القلم الخاص بي، قلمك = الخاص بك، قلمه = الخاص به، قلمها = الخاص بها.</p><p className="source-note">في النحو لا نقول إن الضمير نفسه يعني «الملكية» دائمًا؛ هذا تبسيط لفهم الاستعمال، وسندرس إعرابه بالتفصيل لاحقًا.</p></>),
  step('attached-verbs','14–15. الضمير المتصل بالفعل','الضمائر المتصلة','✍️',<><Compare a="كتبتُ الدرسَ." b="كتبنا الدرسَ." an="التاء تدل على المتكلم: أنا كتبتُ" bn="نا تدل على جماعة المتكلمين"/><p><strong>ساعدَهُ المعلمُ.</strong> الهاء تعود على شخص وقع عليه فعل المساعدة.</p><Rule>الضمير المتصل بالفعل لا يؤدي وظيفة واحدة دائمًا.</Rule><p><strong>كتبتُ:</strong> التاء تدل على من قام بالكتابة. لكن <strong>ساعدني خالدٌ / ساعده المعلمُ / أحبها</strong>: الضمير يدل على من وقع عليه الفعل.</p><p className="source-note">قد تكون له وظائف نحوية مختلفة. سنتعلم إعرابها بالتفصيل عندما يصبح الطالب أقوى في الإعراب، فلا ندخل الآن في التصنيفات المتقدمة.</p></>),
  step('attached-particles','16. الضمير المتصل بالحرف','الضمائر المتصلة','🧩',<><div className="chip-grid">{['لهُ','منهُ','عليهِ','إليكَ','معهُ','عليها','معهم'].map(x=><bdi key={x}>{x}</bdi>)}</div><p><strong>ذهبتُ معهُ.</strong> الهاء ضمير متصل.</p><p><strong>سلَّمتُ عليها.</strong> الهاء في عليها ضمير متصل يدل على مؤنث.</p><p><strong>تحدثتُ معهم.</strong> هم ضمير متصل في كلمة معهم.</p></>),
  step('compare-types','17–18. المنفصل والمتصل','الفرق والاستخدام','⚖️',<><p><strong>كتابي – كتابنا – كتابكَ – كتابكِ – كتابهُ – كتابها – كتابهم</strong>: الضمير جزء من الكلمة، فهو متصل.</p><Compare a="هو طالبٌ. / أنا أقرأُ." b="كتابُهُ جديدٌ. / كتابي مفيدٌ." an="هو وأنا: ضميران منفصلان" bn="الهاء والياء: ضميران متصلان"/></>),
  step('reference','19. مرجع الضمير','الفرق والاستخدام','🔎',<><Rule>مرجع الضمير: الاسم الذي يعود عليه الضمير.</Rule><p><strong>دخلَ سامرٌ إلى غرفتهِ.</strong> الهاء في غرفته تعود على سامر.</p><p><strong>فتحتْ سارةُ كتابَها.</strong> الهاء في كتابها تعود على سارة.</p><p><strong>وصلَ الطلابُ إلى صفهم.</strong> هم في صفهم يعود على الطلاب.</p></>),
  step('agreement','20–22. توافق الضمير','الفرق والاستخدام','🤝',<><h3>الضمير والفعل</h3><div className="chip-grid">{['أنا أكتبُ','نحن نكتبُ','أنتَ تكتبُ','أنتِ تكتبينَ','هو يكتبُ','هي تكتبُ','هما يكتبانِ','هم يكتبونَ','هنَّ يكتبنَ'].map(x=><bdi key={x}>{x}</bdi>)}</div><p>لا تقل: <del>هو تكتبُ</del>؛ الصحيح: <strong>هو يكتبُ</strong>. ولا تقل: <del>هي يكتبُ</del>؛ الصحيح: <strong>هي تكتبُ</strong>.</p><h3>المذكر والمؤنث، والمفرد والمثنى والجمع</h3><p>خالدٌ → هو، سارةُ → هي، خالدٌ وسامرٌ → هما، سارةُ ومريمُ → هما، الطلابُ → هم، الطالباتُ → هنَّ. لاحظ أن هما للمذكر والمؤنث.</p></>),
  step('conceptual','23. الفرق بين المتكلم والمخاطب والغائب','الفرق والاستخدام','🎭',<><p>تخيل أن خالدًا يتحدث مع سامر عن أحمد: <strong>أنا أدرسُ</strong> = خالد المتكلم. <strong>أنتَ تدرسُ</strong> = سامر المخاطب. <strong>هو يدرسُ</strong> = أحمد الغائب.</p><Rule>أنا أتحدث → متكلم<br/>أنا أتحدث إليك → مخاطب<br/>أنا أتحدث عنه → غائب</Rule></>),
  step('hidden','24. الضمير المستتر: فكرة أولية','الفرق والاستخدام','🌫️',<><Rule>مستتر: غير ظاهر في الكلام، ولكننا نفهمه.</Rule><p><strong>أكتبُ الدرسَ.</strong> من يكتب؟ أنا. كلمة أنا غير موجودة، لكن نفهمها داخل الفعل. في الإعراب المتقدم: <strong>الفاعل ضمير مستتر تقديره أنا.</strong></p><p><strong>اكتبْ واجبَكَ.</strong> من سيكتب؟ أنتَ. نقول: <strong>ضمير مستتر تقديره أنتَ.</strong></p><p className="source-note">لا نحتاج الآن إلى حفظ جميع قواعد الضمير المستتر. المطلوب فقط فهم أن الضمير قد يكون ظاهرًا أو مستترًا، وسنعود إليه بالتفصيل في دروس متقدمة.</p></>),
  step('errors','الأخطاء الشائعة وتصحيحها','الفرق والاستخدام','⚠️',<><Error bad="مريمُ مجتهدةٌ، هو تدرسُ كثيرًا." good="مريمُ مجتهدةٌ، هي تدرسُ كثيرًا." note="مريم مؤنث."/><Error bad="خالدٌ وسامرٌ مجتهدان، هم يدرسان." good="خالدٌ وسامرٌ مجتهدان، هما يدرسان." note="نتحدث عن اثنين."/><Error bad="اعتبار الهاء في كتابُهُ ضميرًا منفصلًا." good="الهاء ضمير متصل." note="هي جزء متصل بالكلمة."/><p>أنتَ للمذكر المفرد، وأنتِ للمؤنث المفرد. هم لجماعة الذكور، وهنَّ لجماعة الإناث.</p></>),
  step('solved','ثانيًا: أمثلة محلولة','أمثلة محلولة','💡',<RevealList items={solved}/>),
  step('activities','ثالثًا: النشاط التطبيقي','التطبيق والأنشطة','🧠',<Activities answers={activityAnswers} checked={activityChecked} setAnswers={setActivityAnswers} setChecked={setActivityChecked}/>),
  step('identify','كيف أتعرف إلى الضمير في الجملة؟','التطبيق والأنشطة','🕵️',<><ol><li>ابحث عن كلمة مستقلة من الضمائر الاثني عشر.</li><li>انظر إلى أواخر الأسماء والأفعال والحروف: هل اتصل بها ـي أو نا أو ك أو ه أو ها أو هم؟</li><li>اسأل: على من يعود الضمير؟ وهل يدل على متكلم أو مخاطب أو غائب؟</li><li>تحقق من التوافق في الجنس والعدد.</li><li>إن لم يظهر الفاعل، فقد نفهم ضميرًا مستترًا، مثل أكتبُ → أنا، واكتبْ → أنتَ.</li></ol><p>التحويل من الاسم الظاهر: خالد → هو، سارة → هي، خالد وسامر → هما، الطلاب → هم، الطالبات → هنَّ.</p></>),
  step('final-test','رابعًا: اختبار نهاية الدرس','اختبر نفسك','✅',<OfficialTest answers={testAnswers} checked={testChecked} setAnswers={setTestAnswers} onCheck={()=>setTestChecked(true)}/>),
  step('teacher','خامسًا: منطقة خاصة بالمعلم','منطقة المعلم','🔐',<TeacherArea/>),
  step('summary','الخلاصة للحفظ السريع','الخلاصة','⭐',<Summary/>),
 ]
 return <LessonFlow steps={steps} onProgressChange={onProgressChange} onFinish={onFinish} lessonTitle="الضمائر المنفصلة والمتصلة" lessonNumber="٥" lessonEyebrow="الدرس الخامس" />
}

function step(id:string,title:string,group:string,icon:string,content:ReactNode):LessonStepDefinition{return{id,title,shortTitle:title.replace(/^\d+[–-]?\d*\.\s*/,''),group,icon,description:'تعلم بالتدرج، ثم طبّق ما فهمته.',render:()=>content}}
function Rule({children}:{children:ReactNode}){return <div className="rule-box"><strong>قاعدة</strong><p>{children}</p></div>}
function Compare({a,b,an,bn}:{a:string;b:string;an:string;bn:string}){return <div className="pronoun-compare"><article><bdi>{a}</bdi><span>{an}</span></article><article><bdi>{b}</bdi><span>{bn}</span></article></div>}
function PronounTable({rows}:{rows:string[][]}){return <div className="table-scroll"><table className="pronoun-table"><thead><tr><th>القسم</th><th>الضمير</th><th>لمن؟</th><th>مثال</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r[1]}${i}`}>{r.map(x=><td key={x}><bdi>{x}</bdi></td>)}</tr>)}</tbody></table></div>}
function Error({bad,good,note}:{bad:string;good:string;note:string}){return <div className="error-pair"><p>❌ <del>{bad}</del></p><p>✅ <strong>{good}</strong></p><small>{note}</small></div>}
function RevealList({items}:{items:string[][]}){const [open,setOpen]=useState<Record<number,boolean>>({});return <div className="worked-examples">{items.map((x,i)=><article className="worked-example" key={x[0]}><div><span className="activity-number">{i+1}</span><bdi>{x[0]}</bdi></div><button className="button button--ghost" type="button" onClick={()=>setOpen(o=>({...o,[i]:!o[i]}))}>{open[i]?'إخفاء الحل':'أظهر الحل'}</button>{open[i]&&<p className="activity-feedback activity-feedback--good">{x[1]}</p>}</article>)}</div>}
function Activities({answers,checked,setAnswers,setChecked}:{answers:Record<string,string>;checked:Record<string,boolean>;setAnswers:(x:Record<string,string>)=>void;setChecked:(x:Record<string,boolean>)=>void}){const groups=[{id:'a1',title:'النشاط الأول: اختر الضمير المناسب',items:[['خالدٌ طالبٌ مجتهدٌ. (هو – هي) يحبُّ العلمَ.','هو'],['مريمُ طالبةٌ نشيطةٌ. (هو – هي) تساعدُ أمها.','هي'],['خالدٌ وسامرٌ صديقان. (هما – هم) يلعبانِ.','هما'],['الطالباتُ مجتهداتٌ. (هم – هنَّ) يدرسنَ.','هنَّ'],['أنا وأخي نذهب إلى المدرسة. (نحن – أنتم) ندرسُ معًا.','نحن']]},{id:'a2',title:'النشاط الثاني: حدد نوع الضمير',items:[['أنا أحبُّ مدرستي.','منفصل'],['هذا كتابي (الياء).','متصل'],['هو يقرأُ القصةَ.','منفصل'],['أخذَ سامرٌ قلمه (الهاء).','متصل'],['نحن نحبُّ وطننا: نحن / نا.','منفصل، متصل']]},{id:'a3',title:'النشاط الثالث: استبدل الاسم بضمير مناسب',items:[['خالد → ______ يدرسُ.','هو'],['سارة → ______ تقرأُ.','هي'],['خالد وسامر → ______ يلعبانِ.','هما'],['الطلاب → ______ يكتبونَ.','هم'],['الطالبات → ______ يدرسنَ.','هنَّ']]}];return <div className="activity-list">{groups.map(g=><section className="activity-card" key={g.id}><h3>{g.title}</h3>{g.items.map((it,i)=><label className="activity-row" key={it[0]}><bdi>{i+1}. {it[0]}</bdi><input value={answers[`${g.id}-${i}`]||''} disabled={checked[g.id]} onChange={e=>setAnswers({...answers,[`${g.id}-${i}`]:e.target.value})}/>{checked[g.id]&&<span className="answer-mark is-good">الإجابة: {it[1]}</span>}</label>)}<button type="button" className="button button--primary" onClick={()=>setChecked({...checked,[g.id]:true})}>تحقق من النشاط</button></section>)}</div>}
function OfficialTest({answers,checked,setAnswers,onCheck}:{answers:Record<number,string>;checked:boolean;setAnswers:(x:Record<number,string>)=>void;onCheck:()=>void;}){return <div className="official-test" data-testid="lesson5-official-test"><div className="official-test__intro"><strong>اختبار نهاية الدرس</strong><span>٢٠ سؤالًا</span><p>أجب عن الأسئلة العشرين كاملة، مع المحافظة على الفئات والترقيم الرسمي.</p></div>{questions.map(q=>{const heading=q.number===1||questions[q.number-2]?.section!==q.section;return <div key={q.number}>{heading&&<h3>{q.section}</h3>}<fieldset className="official-question" disabled={checked}><legend><span className="question-number">{q.number}</span> {q.prompt}</legend>{q.options?<div className="quiz__options">{q.options.map(o=><label key={o}><input type="radio" name={`q${q.number}`} checked={answers[q.number]===o} onChange={()=>setAnswers({...answers,[q.number]:o})}/><span>{o}</span></label>)}</div>:<textarea rows={3} value={answers[q.number]||''} onChange={e=>setAnswers({...answers,[q.number]:e.target.value})}/>} {checked&&<p className="activity-feedback activity-feedback--good">الإجابة النموذجية: {q.answer}</p>}</fieldset></div>})}<button type="button" className="button button--primary" onClick={onCheck}>تحقق من الاختبار</button></div>}
function TeacherArea(){return <TeacherSpace><div className="teacher-material"><h3>إجابات النشاط التطبيقي</h3><p><strong>النشاط الأول:</strong> 1. هو، 2. هي، 3. هما، 4. هنَّ، 5. نحن.</p><p><strong>النشاط الثاني:</strong> 1. أنا منفصل، 2. الياء في كتابي متصل، 3. هو منفصل، 4. الهاء في قلمه متصل، 5. نحن منفصل ونا في وطننا متصل.</p><p><strong>النشاط الثالث:</strong> هو يدرسُ؛ هي تقرأُ؛ هما يلعبانِ؛ هم يكتبونَ؛ هنَّ يدرسنَ.</p><h3>الإجابات النموذجية لاختبار نهاية الدرس</h3><ol>{questions.map(q=><li key={q.number}><strong>{q.number}.</strong> {q.answer}</li>)}</ol><h3>ملاحظات للمعلم</h3><p><strong>لا تبدأ بالإعراب المعقد.</strong> الهدف: ما الضمير؟ لمن يدل؟ هل هو منفصل أم متصل؟ تؤجل عبارات «ضمير متصل مبني في محل جر بالإضافة» و«في محل نصب مفعول به» إلى ما بعد تأسيس الإعراب.</p><p><strong>ركز على المتكلم والمخاطب والغائب:</strong> قل: أنا معلمٌ، ثم أنتَ طالبٌ، ثم هو طالبٌ، واسأل في كل مرة.</p><p><strong>استخدم الأسماء قبل الضمائر:</strong> أحمد → هو، مريم → هي، أحمد وسامر → هما، مريم وسارة → هما، الطلاب → هم، الطالبات → هنَّ.</p><h3>أخطاء متوقعة من الطالب وتصحيحها</h3><ul><li>هم بدل هما: كرر «اثنان → هما، جماعة ذكور → هم».</li><li>هو وهي: «ولد واحد → هو، بنت واحدة → هي».</li><li>هم وهنَّ: «طلاب → هم، طالبات → هنَّ».</li><li>عدم رؤية المتصل: اكتب «كتاب + ه = كتابه، كتاب + ها = كتابها، كتاب + ي = كتابي، كتاب + نا = كتابنا»، ثم ضع خطًا تحت الجزء المضاف.</li></ul><h3>اقتراح لإعادة التدريس — الطريقة العلاجية</h3><ol><li><strong>المرحلة الأولى:</strong> أنا – نحن – أنتَ – أنتِ – هو – هي فقط.</li><li><strong>المرحلة الثانية:</strong> أضف أنتما – أنتم – أنتنَّ – هما – هم – هنَّ.</li><li><strong>المرحلة الثالثة:</strong> انتقل إلى ـي – نا – ـكَ/ـكِ – ـه – ـها – ـهم، مع كتابي وكتابنا وكتابك وكتابه وكتابها وكتابهم.</li></ol><p>لا ينتقل الطالب إلى التفاصيل الإعرابية قبل أن يميز المنفصل والمتصل بسهولة.</p><h3>واجب منزلي مقترح</h3><p><strong>أ. ضع الضمير المناسب:</strong> أحمدٌ مجتهدٌ. ___ يدرس يوميًا؛ سارة تحب الرسم. ___ ترسم زهرة؛ أحمد وسامر صديقان. ___ يلعبان؛ الطالبات في الصف. ___ يستمعن؛ أنا وأخي نقرأ. ___ نحب الكتب.</p><p><strong>ب. استخرج الضمير:</strong> هذا قلمي؛ نحن نحب وطننا؛ هو يساعد والده؛ هي رتبت غرفتها؛ أنتم طلاب مجتهدون.</p><p><strong>ج. كوّن خمس جمل</strong> باستخدام: أنا – أنتَ – هي – نحن – هم.</p></div></TeacherSpace>}
function Summary(){return <><EducationalCard title="خلاصة للحفظ السريع" eyebrow="الخلاصة"><p><strong>الضمير</strong> يدل على متكلم أو مخاطب أو غائب.</p><p><strong>المتكلم:</strong> أنا، نحن. <strong>المخاطب:</strong> أنتَ، أنتِ، أنتما، أنتم، أنتنَّ. <strong>الغائب:</strong> هو، هي، هما، هم، هنَّ.</p><p><strong>المنفصل:</strong> كلمة مستقلة مثل أنا وهو ونحن. <strong>المتصل:</strong> يتصل بكلمة مثل كتابي وكتابه ووطننا وساعدني. <strong>المستتر:</strong> لا يظهر لكن نفهمه: أكتبُ، والفاعل ضمير مستتر تقديره أنا.</p><ol><li>المتصل قد يتصل باسم أو فعل أو حرف.</li><li>انتبه إلى المذكر والمؤنث والمفرد والمثنى والجمع.</li><li>هما للمثنى المذكر والمؤنث.</li><li>أحكام المستتر التفصيلية مؤجلة.</li></ol></EducationalCard><blockquote className="grammar-quote golden-rule"><p className="source-kicker">الفكرة الذهبية:</p><p><strong>الضمير يجعل الكلام أسهل وأجمل، ويجنبنا تكرار الاسم؛ فابحث عمّن يدل عليه، ثم اسأل: أهو منفصل أم متصل أم مفهوم مستتر؟</strong></p></blockquote></>}
