import { readFileSync } from 'node:fs'
const lesson=readFileSync('src/lessons/LessonFive.tsx','utf8');const registry=readFileSync('src/lessons/registry.ts','utf8');const app=readFileSync('src/app/App.tsx','utf8');const failures=[]
const need=(text,label=text)=>{if(!lesson.includes(text))failures.push(`Missing Lesson 5 source coverage: ${label}`)}
for(const phrase of ['الدرس الخامس: الضمائر المنفصلة والمتصلة','أهداف الدرس','ما الضمير؟','الاسم الظاهر والضمير','المتكلم والمخاطب والغائب','الضمائر المنفصلة','أنا، نحن، أنتَ، أنتِ، أنتما، أنتم، أنتنَّ، هو، هي، هما، هم، هنَّ','12 ضميرًا منفصلًا','الضمير المتصل','كتابي = كتاب + ي','كتابنا = كتاب + نا','كتابكَ = كتاب + كَ','كتابكِ = كتاب + كِ','كتابهُ = كتاب + ه','كتابها = كتاب + ها','كتابكم = كتاب + كم','كتابهم = كتاب + هم','كتابهنَّ = كتاب + هنَّ','كتبتُ الدرسَ','ساعدني خالدٌ','ساعده المعلمُ','أحبها','لهُ','منهُ','عليهِ','إليكَ','معهُ','عليها','معهم','مرجع الضمير','دخلَ سامرٌ إلى غرفتهِ','أنا أكتبُ','نحن نكتبُ','أنتَ تكتبُ','أنتِ تكتبينَ','هو يكتبُ','هي تكتبُ','هما يكتبانِ','هم يكتبونَ','هنَّ يكتبنَ','المذكر والمؤنث','المفرد والمثنى والجمع','الضمير المستتر','أكتبُ الدرسَ','اكتبْ واجبَكَ','لا نحتاج الآن إلى حفظ جميع قواعد الضمير المستتر','كيف أتعرف إلى الضمير','أمثلة محلولة','النشاط الأول: اختر الضمير المناسب','النشاط الثاني: حدد نوع الضمير','النشاط الثالث: استبدل الاسم بضمير مناسب','اختبار نهاية الدرس','إجابات النشاط التطبيقي','الإجابات النموذجية لاختبار نهاية الدرس','أخطاء متوقعة من الطالب','اقتراح لإعادة التدريس','الطريقة العلاجية','واجب منزلي مقترح','خلاصة للحفظ السريع','الفكرة الذهبية:'])need(phrase)
const qBlock=lesson.slice(lesson.indexOf('const questions:'),lesson.indexOf('export function LessonFive'));const questionCount=(qBlock.match(/number:\d+/g)||[]).length;if(questionCount!==20)failures.push(`Official final test has ${questionCount}, expected 20.`)
const activityCount=(lesson.match(/title:'النشاط (الأول|الثاني|الثالث)/g)||[]).length;if(activityCount!==3)failures.push(`Expected all 3 source activities; found ${activityCount}.`)
const steps=lesson.slice(lesson.indexOf('const steps:'),lesson.indexOf('return <LessonFlow'));const stepCount=(steps.match(/step\('/g)||[]).length;if(stepCount<20)failures.push(`Sequential flow too short: ${stepCount} steps.`)
for(const group of ['البداية','مفهوم الضمير','الضمائر المنفصلة','الضمائر المتصلة','الفرق والاستخدام','أمثلة محلولة','التطبيق والأنشطة','اختبر نفسك','منطقة المعلم','الخلاصة'])if(!steps.includes(`'${group}'`))failures.push(`Missing outline group: ${group}`)
if(!lesson.includes('<TeacherSpace>'))failures.push('Teacher material is not protected by TeacherSpace.');if(/SectionNav|scrollIntoView|IntersectionObserver/.test(lesson))failures.push('Forbidden navigation primitive found.')
if(!registry.includes("id: 'lesson-5'")||!registry.includes('الدرس الخامس: الضمائر المنفصلة والمتصلة'))failures.push('Lesson 5 is not registered.');if(!app.includes('LessonFive')||!app.includes("lesson.id === 'lesson-5'"))failures.push('Lesson 5 is not routed through LessonShell.')
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log(`Lesson 5 source audit passed: ${stepCount} sequential steps, 3 official activities (15 prompts), complete 20-question final test, teacher answer key, expected errors, remediation, homework, summary, and golden idea.`)
